# Generated by Django 4.2.2 on 2023-07-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='forUser_uiid',
            field=models.CharField(default='Hey', max_length=255),
        ),
    ]
