# Generated by Django 4.2.2 on 2023-07-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_yazar_is_active_alter_yazar_foruser_uiid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazar',
            name='is_active',
        ),
    ]
