# Generated by Django 4.2.2 on 2023-07-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yazar',
        ),
    ]
