# Generated by Django 4.2.2 on 2023-07-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
