# Generated by Django 4.2.2 on 2023-07-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_my_blog',
            field=models.BooleanField(default=False),
        ),
    ]
