# Generated by Django 4.2.2 on 2023-07-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_myuser_is_my_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_my_blog',
        ),
    ]
