# Generated by Django 4.2.2 on 2023-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_remove_myuser_is_my_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sekil',
            field=models.ImageField(blank=True, default='rootstatic/img/default-man.jpg', null=True, upload_to='main/uploads/%d/%m/%Y', verbose_name='Şəkil'),
        ),
    ]
