# Generated by Django 4.2.2 on 2023-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_myuser_sekil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sekil',
            field=models.ImageField(blank=True, default='rootstatic/img/default-man.jpg', null=True, upload_to='main/uploads/myuser/images/%d/%m/%Y', verbose_name='Şəkil'),
        ),
    ]
