# Generated by Django 4.2.2 on 2023-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(verbose_name='Aktiv status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
