# Generated by Django 4.2.2 on 2023-06-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lastmodified',
            field=models.DateField(auto_now=True, verbose_name='Sonuncu deyişiklik tarixi'),
        ),
    ]
