# Generated by Django 4.2.2 on 2023-06-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blog_lastmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='borndate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Yaranma tarixi'),
        ),
    ]
