# Generated by Django 4.2.2 on 2023-06-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_blog_snippet_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='likeSayi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
