# Generated by Django 4.2.2 on 2023-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_yazar_blog_likesayi'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sevimliSayi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
