# Generated by Django 4.2.2 on 2023-07-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_delete_yazar_remove_blog_likesayi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kateqoriya adı'),
        ),
    ]
