# Generated by Django 4.2.2 on 2023-07-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.CharField(default='Davamını oxumaq üçün klikləyin...', max_length=50),
        ),
    ]
