# Generated by Django 4.2.2 on 2023-07-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_alter_blog_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='titleofblog',
        ),
    ]
