# Generated by Django 4.2.2 on 2023-08-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_alter_blog_borndate_alter_blog_lastmodified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Məqaləni', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriyanı', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.category', verbose_name='Kateqoriya seç'),
        ),
    ]
