# Generated by Django 4.2.2 on 2023-08-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
    ]
