# Generated by Django 4.2.4 on 2023-09-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_alter_blog_options_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likedCount',
            field=models.PositiveIntegerField(default=0, verbose_name='Bəyənmə sayı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='unlikedCount',
            field=models.PositiveIntegerField(default=0, verbose_name='Bəyənmə sayı'),
        ),
    ]
